config/routes.rb
Rottenpotatoes::Application.routes.draw do
  root to: 'dashboard#index'
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :tasks do
    collection do
      get 'my_profile'
      get 'delete_all'
      get 'accept'
      get 'delete_accepted'
      get 'completed'
    end
  end 
end

app/models/task.rb
class Task < ActiveRecord::Base
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  belongs_to :user

  validates :name, :hours, :location, :price, :description, :presence => true
  validates :hours, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 } 


  def self.find_tasks(school, pay)
    if (pay == nil)
      return Task.joins(:user).where(:users => {school: school})
    else
      if (pay == "less_than_20")
        return Task.joins(:user).where(:users => {school: school}, :price => -1...20, :accepted => false)
      elsif (pay == "20-50")
        return Task.joins(:user).where(:users => {school: school}, :price => 20..50, :accepted => false)
      else
        return Task.joins(:user).where(:users => {school: school}, :price => 50...Float::INFINITY, :accepted => false)
      end 
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    if !user_signed_in?
      return redirect_to root_path
    end

    @task = Task.find params[:id]
    @user_id = @task.user_id
    @id = @task.id
    @name = @task.name
    @description = @task.description
    @hours = @task.hours
    @location = @task.location
    @price = @task.price
    @created_at = @task.created_at
    @user_accepted_id = @task.user_accepted_id
    
    if @user_accepted_id != nil
      @user = User.find @user_accepted_id.to_i
      @user_accepted_uni = @user.email
    end
  end
 
  def index
    if (!user_signed_in?)
      return redirect_to root_path
    end

    if Task.joins(:user).exists?(:users => {school: current_user.school})
      @tasks = Task.find_tasks(current_user.school, params[:pay])
    else
      @tasks = []
    end


    if @tasks.length > 0 && (@tasks.length - @tasks.where(:accepted => true, :completed => false).length - @tasks.where(:completed => true).length > 0)
      @available_tasks = @tasks.length - @tasks.where(:accepted => true, :completed => false).length - @tasks.where(:completed => true).length
    else
      @available_tasks = 0
    end

    if (params[:sort] != nil)
      @sort = params[:sort]
    end
  
    if (@sort == "created_at_old" && @tasks != [])
      @sort_oldest_date_header = ''
      @tasks = @tasks.order(created_at: :asc)
    elsif (@sort == "created_at_new" && @tasks != [])
      @sort_recent_date_header = ''
      @tasks = @tasks.order(created_at: :desc)
    elsif (@sort == "lowest_to_highest_pay" && @tasks != [])
      @sort_low_high_price_header = ''
      @tasks = @tasks.order(price: :asc)
    elsif (@sort == "highest_to_lowest_pay" && @tasks != [])
      @sort_high_low_price_header = ''
      @tasks = @tasks.order(price: :desc)
    end
    @accepted_tasks = Task.where(user_accepted_id: current_user.id) == nil ? [] : Task.where(user_accepted_id: current_user.id)
    session[:sort] = @sort
  end

  def new
    if !user_signed_in?
      return redirect_to root_path
    end
    @user_id = current_user.id
  end

  def create
    if !user_signed_in?
      return redirect_to root_path
    end

    task = Task.new(task_params)
    valid = task.valid?

    if !valid
      flash[:warning] = task.errors.full_messages[0]
      return redirect_to new_task_path
    else
      @task = Task.create(task_params)
      @created_at = Time.now
      flash[:notice] = "A task was successfully created."
      return redirect_to my_profile_tasks_path
    end
  end

  def edit
    if !user_signed_in?
      return redirect_to root_path 
    elsif Task.where(id: params[:id]).empty? || (!Task.where(id: params[:id]).empty? && (Task.find(params[:id]).user_id != current_user.id))
      return redirect_to root_path 
    end

    @task = Task.find params[:id]
    @user_id = current_user.id
    @id = @task.id
    @name = @task.name
    @description = @task.description
    @hours = @task.hours
    @location = @task.location
    @price = @task.price
    @user_accepted_id = @task.user_accepted_id
    @created_at = Time.now
  end

  def update
    if !user_signed_in?
      return redirect_to root_path 
    end

    @task = Task.find(params[:id])
    task = Task.new(task_params)

    if task.valid?
      @task.update_attributes(task_params)
      flash[:notice] = task_params
      flash[:notice] = "A task was successfully updated."
      redirect_to my_profile_tasks_path
    else
      flash[:notice] = task.errors.full_messages[0]
      redirect_to edit_task_path(params[:id])
    end
  end

  def destroy
    if !user_signed_in?
      return redirect_to root_path 
    end
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "A task was deleted."
    redirect_to my_profile_tasks_path
  end

  def my_profile
    if !user_signed_in?
      return redirect_to root_path
    end
    if (user_signed_in?)
      @my_tasks = Task.where(user_id: current_user.id) == nil ? [] : Task.where(user_id: current_user.id)
      @first_name = current_user.fname
      @last_name = current_user.lname
      @school = current_user.school
      @email = current_user.email

      @accepted_tasks = Task.where(user_accepted_id: current_user.id) == nil ? [] : Task.where(user_accepted_id: current_user.id)
    end
  end

  def delete_all
    if !user_signed_in?
      return redirect_to root_path
    end

    Task.where(user_id: current_user.id).delete_all
    flash[:notice] = "You have removed all your tasks!"
    redirect_to my_profile_tasks_path
  end

  def accept
    if !user_signed_in?
      return redirect_to root_path
    end

    @task = Task.find((params["format"]).to_i)
    @task.accepted = true
    @task.user_accepted_id = current_user.id
    @task.update_attributes(task_params_accept)

    redirect_to my_profile_tasks_path
  end

  def delete_accepted
    if !user_signed_in?
      return redirect_to root_path
    end

    @task = Task.find((params["format"]).to_i)
    @task.accepted = false
    @task.user_accepted_id = nil
    @task.update_attributes(task_params_accept)

    redirect_to my_profile_tasks_path
  end

  def completed
    if !user_signed_in?
      return redirect_to root_path
    end

    @task = Task.find((params["format"]).to_i)
    @task.completed = true
    @task.update_attributes(task_params_accept)

    redirect_to my_profile_tasks_path
  end

  private
  def task_params
      # This allows you to create and edit a new task but not accept and mark as complete
      params.require(:task).permit(:name, :hours, :location, :price, :description, :user_id, :completed, :user_accepted_id, :sort)
      
      # This allows you to accept and mark as complete but not create and edit a new task
      # params.permit(:name, :hours, :location, :price, :description, :user_id, :completed, :user_accepted_id, :sort)
  end

  private
  def task_params_accept
      # This allows you to accept and mark as complete but not create and edit a new task
      params.permit(:name, :hours, :location, :price, :description, :user_id, :completed, :user_accepted_id, :sort)
  end
end

app/views/tasks/edit.html.erb
<link rel="stylesheet" type="text/css" href="/app/stylesheets/application.css">

<%= render 'shared/navbar' %>
<div class="row">
  <div class="col-12 text-center">
    <h1>Edit My Task</h1>
  </div>
</div>

<div>
  <div class="col-12">
    <%= form_tag task_path(@id), method: :put, class: 'form' do %>
      <%= label :task, :name, 'Task Name', class: 'col-form-label' %>
      <%= text_field :task, :name, value: @name, class: 'form-control'%>
      <%= label :task, :hours, 'Time Needed', class: 'col-form-label' %>
      <%= text_field :task, :hours, value: @hours, class: 'form-control' %>
      <%= label :task, :location, 'Location', class: 'col-form-label' %>
      <%= text_field :task, :location, value: @location, class: 'form-control' %>
      <%= label :task, :price, 'Price', class: 'col-form-label' %>
      <%= text_field :task, :price, value: @price, class: 'form-control' %>
      <%= label :task, :description, 'Description', class: 'col-form-label' %>
      <%= text_field :task, :description, value: @description, class: 'form-control' %>
      <%= number_field :task, :user_id, class: 'form-control', value: @user_id, type: :hidden %>

      <div class="text-center">
        <%= link_to 'Delete Task', task_path(@id), method: :delete, class: 'btn btn-danger' %> 
        <%= submit_tag 'Update', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<link rel="stylesheet" type="text/css" href="/app/stylesheets/application.css">

<%= render 'shared/navbar' %>
<div class = "container">
  <div class="row">
    <div class="col-12 text-center" id="index-title">
      <h1>Tasks</h1>
    </div>
  </div>

  <div class="row">
        <div class="col-3">
          <div class = "top-header">
            <h3> Filter </h3> 
          </div>
          <div>
            <%= link_to 'Less than $20', tasks_path(:pay=>"less_than_20"), class: 'btn filter-btn' %> <br/>
            <%= link_to '$20-$50', tasks_path(:pay=>"20-50"), class: 'btn filter-btn' %> <br/>
            <%= link_to 'More than $50', tasks_path(:pay=>"over_50"), class: 'btn filter-btn' %>
          </div>
          <div class = "top-header">
            <h3> Sort </h3>
          </div>
          <div>
            <div><b>Date</b></div>
          </div>
          <div>
            <div class = "<%=@sort_oldest_date_header%>">
              <%= link_to 'Sort By Oldest', tasks_path(:sort=>"created_at_old"), id: 'date_header_old', class: 'btn filter-btn' %>
            </div>
            <div class = "<%=@sort_recent_date_header%>">
              <%= link_to 'Sort By Newest', tasks_path(:sort=>"created_at_new"), id: 'date_header_new', class: 'btn filter-btn' %>
            </div>
          </div>
          <div>
            <div><b>Price</b></div>
          </div>
          <div>
            <div class = "<%=@sort_low_high_price_header%>">
              <%= link_to 'Sort Low to High', tasks_path(:sort=>"lowest_to_highest_pay"), id: 'price_header_new', class: 'btn filter-btn' %>
            </div>
            <div class = "<%=@sort_high_low_price_header%>">
              <%= link_to 'Sort High to Low', tasks_path(:sort=>"highest_to_lowest_pay"), id: 'price_header_new', class: 'btn filter-btn' %>
            </div>
          </div>
        </div>

        <div class = "col-md-9">
          <br/>
          <div>
            <h5>Available tasks: <%= @available_tasks %> </h5>
          </div>
          <div class = "row">
            <% @tasks.each_with_index do |t, i| %>
              <% if t.user_accepted_id == nil && t.completed == false %>
                <div class="col-5">
                  <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h3 class="card-text font-weight-bold"><%= t.name %></h3>
                      <h5 class="card-title"><%= t.user.fname %> <%= t.user.lname %></h5>
                      <h6 class="card-subtitle mb-2 text-muted"><%= t.user.email %></h6>
                      <p class="card-text"><%= t.description %></p>
                      <p class="card-text font-weight-bold">Time Needed: <%= t.hours %> hr(s)</p>
                      <p class="card-text font-weight-bold">Location: <%= t.location %></p>
                      <p class="card-text font-weight-bold">Pay: $<%= t.price %></p>
                      <p class="card-text font-weight-bold">Posted <%= time_ago_in_words(t.created_at) %> ago</p>
                      <% if t.user != current_user && @accepted_tasks.count - @accepted_tasks.select{|task| task.completed == true}.size <=3 %>
                        <%= link_to 'Accept task', accept_tasks_path(t.id), class: 'btn btn-outline-dark' %> 
                      <% end %>
                      <% if t.user != current_user && @accepted_tasks.count  - @accepted_tasks.select{|task| task.completed == true}.size >3 %>
                        <%= link_to 'Accept task', accept_tasks_path(t.id), class: 'btn btn-outline-dark disabled' %> 
                      <% end %>
                      </div>
                  </div>
                </div>
              <%end%>
            <% end %>

            <% if @tasks.length == 0 %>
            <div class="col-12">
              There are no tasks available at the moment.
            </div>
            <% end %>
          </div>
        </div>    
  </div>
</div>

app/views/tasks/my_profile.html.erb
<link rel="stylesheet" type="text/css" href="/app/stylesheets/application.css">

<%= render 'shared/navbar' %>
<div class="row">
    <div class="col-12 text-center" id="profile-title">
        <h1>My Profile</h1>
    </div>
</div>

<div class="row" id="account-info">
    <div class = "col-md-2">
    </div>
    <div class = "col-md-5">
        <h1>Account Information</h1>
        <b>Name: </b><%= @first_name %> <%= @last_name %> <br/>
        <b>Email:</b> <%= @email %>  <br/>
        <b>User ID:</b> <%= current_user.id %>  <br/>
        <b>University:</b> <%= @school %>
    </div>
    <div class = "col-md-3">
    <%= link_to 'Edit', edit_user_registration_path, class: 'btn btn-primary' %>
    </div>
</div>


<div class="tasks-section">
    <div class = "row">
        <div class = "col-md-3">
            <h1>My Tasks</h1>
        </div>
        <div class = "col-md-9">
            <div class = "row">
                <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %> 
                <%= link_to 'Delete All Tasks', delete_all_tasks_path, :method => :get, class: 'btn btn-danger delete-btn', data: {confirm: "Are you sure you want to delete all your tasks?"} %>
            </div>
        </div>
    </div>
    <br/>
    <div class = "row">
        <div class= "col-6">
            <div class="row">
                <h2>Tasks Requested</h2>
            </div>
            <div class = "col-12">
                <% @my_tasks.each do |t| %>
                    <div class ="task-prof col-lg-10">
                        <%= link_to t.name, task_path(t.id) %>
                        <% if t.completed %>
                            completed!
                        <% elsif t.user_accepted_id != nil %>
                            accepted
                        <% end %>
                        <div class = "float-right top:50% vertical-center">
                            <%= link_to 'Delete', task_path(t.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this tasks?"} %> 
                        </div>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <h2>Tasks Accepted</h2>
                    <% @accepted_tasks.each do |t| %>
                        <% if !t.completed %>
                            <div class ="task-prof col-lg-10">
                                <%= link_to t.name, task_path(t.id) %>
                                <div class = "float-right top:50% vertical-center">
                                    <%= link_to 'Delete', delete_accepted_tasks_path(t.id), class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this tasks?"} %> 
                                 </div>
                            </div>
                        <% end %>
                    <% end %>
                    <div class ="spacing">
                    </div>
                </div>
            </div>
            <div class = "row">
                <div class="col-12">
                    <h2>Tasks Completed</h2>
                    <% @accepted_tasks.each do |t| %>
                        <% if t.completed %>
                            <div class ="task-prof col-lg-10">
                                <%= link_to t.name, task_path(t.id) %>
                            </div>
                        <% end %>
                    <% end %>
                    <div class ="spacing">
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/tasks/new.html.erb
<link rel="stylesheet" type="text/css" href="/app/stylesheets/application.css">


<%= render 'shared/navbar' %>
<div class="container">
<div class="row">
    <div class="col-12 text-center">
        <h1>Create a Task</h1>
    </div>
</div>

<div class = "row">
  <div class = "col-md-3">
  </div>
  <div class = "col-md-6 add-task">
  <%= form_tag tasks_path, class: 'form' do %>
  <%= label :task, :name, 'Task Name', class: 'col-form-label' %>
  <%= text_field :task, :name, class: 'form-control', autofocus: true%>
  <%= label :task, :hours, 'Time Needed', class: 'col-form-label' %>
  <%= text_field :task, :hours, class: 'form-control' %>
  <%= label :task, :location, 'Location', class: 'col-form-label' %>
  <%= text_field :task, :location, class: 'form-control' %>
  <%= label :task, :price, 'Price', class: 'col-form-label' %>
  <%= text_field :task, :price, class: 'form-control'%>
  <%= label :task, :description, 'Description', class: 'col-form-label' %>
  <%= text_field :task, :description, class: 'form-control' %>
  <%= number_field :task, :user_id, class: 'form-control', value: @user_id, type: :hidden %>


  <div class="text-center">
      <%= link_to 'Cancel', my_profile_tasks_path, class: 'btn btn-warning' %> 
      <%= submit_tag 'Create', class: 'btn btn-create' %>
  </div>

<% end %>
  </div>
  <div class = "col-md-3">
  </div>
</div>
</div>

app/views/tasks/show.html.erb
<link rel="stylesheet" type="text/css" href="/app/stylesheets/application.css">
<%= render 'shared/navbar' %>
<div class="row">
  <div class="col-12 text-center top-header">
    <h1>Task: <%=@name%></h1>
  </div>
</div>
<div class="row">
  <div class="col-12 text-center top-header">
    <% if @user_accepted_id == nil %>
      <h3>Currently assigned to no one</h1>
    <% else %>
      <h3>Currently assigned to user: <%=@user_accepted_uni%></h1>
    <% end %>
  </div>
</div>
<div class="row">
  <div class ="col-3">
  </div>
  <div class="task-info col-6">
      <div class = "descriptor">
        <b>Posted by user_id</b>: <%=@user_id%>
      </div>
      <div class = "descriptor">
        <b>Description</b>: <%=@description%>
      </div>
      <div class = "descriptor">
        <b>Time Needed</b>: <%=@hours%> hr(s)
      </div>
      <div class = "descriptor">
        <b>Location:</b> <%=@location%>
      </div>
      <div class = "descriptor">
        <b>Price:</b> $<%=@price%>
      </div>
      <div class = "descriptor">
        <b>Created At:</b> <%=@created_at%>
      </div>
  </div>
  <div class ="col-3">
  </div>
</div>

<% if @user_id == current_user.id %>
  <div class="row">
    <div class="col-12 text-center edit-task">
      <%= link_to 'Edit Task', edit_task_path(@id), class: 'btn btn-primary' %> 
    </div>
  </div>
<% else %>
  <div class="row">
  <div class="col-12 text-center edit-task">
    <% if @task.completed == false %>
      <%= link_to 'Mark as completed', completed_tasks_path(@id), class: 'btn btn-primary' %>
      <%= link_to 'Unaccept task', delete_accepted_tasks_path(@id), class: 'btn btn-primary' %> 
    <% end %>
  </div>
  </div>
<% end %>