config/routes.rb
Rottenpotatoes::Application.routes.draw do
  root to: 'dashboard#index'
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :tasks do
    collection do
      get 'my_profile'
      get 'delete_all'
      get 'accept'
      get 'delete_accepted'
      get 'completed'
    end
  end 
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-custom">
  <%= link_to 'alma', '/', class: 'navbar-brand' %>
  <% if user_signed_in? %>
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to 'All Tasks', tasks_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Profile', my_profile_tasks_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  <% else %>
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>
    </ul>
  <% end %>
</nav>